# default config.yml
LocationItem: WOOD_SPADE
Team:
  Names:
    - Red
    - Blue
Red:
  Color: Åòc
  Armor: IRON
Blue:
  Color: Åò9
  Armor: DIAMOND
Game:
  SnowBallStacks: 2
  GiveSnowBallNum: 5 #num
  GiveSnowBallTime: 30 #seconds
  GameTime: 5  #minutes
  InvincibleTime: 20  #ticks (20tick = 1second) 
Spectator:
  Height:20