# default config.yml
Mode: random
LocationItem: WOOD_SPADE
Team:
  Names:
    - Red
    - Blue
Red:
  Color: RED
  Armor: IRON
Blue:
  Color: BLUE
  Armor: DIAMOND
Game:
  SnowBallStacks: 2 #stacks
  GiveSnowBallNum: 5 #num
  GiveSnowBallTime: 30 #seconds
  GameTime: 5  #minutes
  InvincibleTime: 20 #ticks (20tick = 1second) 
Item:
  TripleShot:
    Active: false #boolean
    Duration: 20 #sec
    Item: 
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_BLOCK
    Numbers: 0
  Invisible:
    Active: false #boolean
    Duration: 10 #sec
    Item: 
      ==: org.bukkit.inventory.ItemStack
      type: BEACON
    Numbers: 0
  SpeedUp:
    Active: false #boolean
    Duration: 10 #sec
    Item: 
      ==: org.bukkit.inventory.ItemStack
      type: MINECART
    Numbers: 0
  SpawnCannon:
    Active: false #boolean
    Duration: 60 #sec
    Item: 
      ==: org.bukkit.inventory.ItemStack
      type: PUMPKIN
    Numbers: 0
Spectator:
  Height:20 #blocks