name: SnowBallBattle
main: com.gmail.badfalcon610.SnowBallBattle.SnowBallBattle
version: 0.1
commands:
   sbb:
      description: 【管理者専用】雪合戦プラグインの設定あれこれ。
      usage: /sbb
      permission: sbb
      permission-message: You don't have 
      default: op
permissions:
   sbb:
      description: 雪合戦の設定あれこれの変更ができるようになります。
      default: op